services:
  db:
    image: postgres:16
    container_name: preventia-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
  backend:
    build: .
    container_name: preventia-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  db_data:
